#
# Makefile.inc -- Makefile dependencies for chapter 0
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chaptes/000-einleitung/1-frueh.tex				\
	chaptes/000-einleitung/2-kalkuel.tex				\
	chaptes/000-einleitung/3-epsilon.tex				\
	chaptes/000-einleitung/4-cas.tex				\
	chapters/000-einleitung/chapter.tex

