#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/040-analytisch/1-potenzreihen.tex			\
	chapters/040-analytisch/2-rational.tex				\
	chapters/040-analytisch/3-fortsetzung.tex			\
	chapters/040-analytisch/4-laurentreihen.tex			\
	chapters/040-analytisch/chapter.tex

