#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

AUFGABENFILES +=							\
	chapters/040-analytisch/uebungsaufgaben/401.tex			\
	chapters/040-analytisch/uebungsaufgaben/402.tex			\
	chapters/040-analytisch/uebungsaufgaben/403.tex

CHAPTERFILES += 							\
	chapters/040-analytisch/1-potenzreihen.tex			\
	chapters/040-analytisch/11-polynome.tex				\
	chapters/040-analytisch/12-geometrisch.tex			\
	chapters/040-analytisch/13-integration.tex			\
	chapters/040-analytisch/14-analytisch.tex			\
	chapters/040-analytisch/15-reellanalytisch.tex			\
	chapters/040-analytisch/2-rational.tex				\
	chapters/040-analytisch/21-faktorisierung.tex			\
	chapters/040-analytisch/22-partialbruchzerlegung.tex		\
	chapters/040-analytisch/3-fortsetzung.tex			\
	chapters/040-analytisch/31-definition.tex			\
	chapters/040-analytisch/32-fortsetzung.tex			\
	chapters/040-analytisch/33-ueberlagerungen.tex			\
	chapters/040-analytisch/4-laurentreihen.tex			\
	chapters/040-analytisch/41-ring.tex				\
	chapters/040-analytisch/42-laurent.tex				\
	chapters/040-analytisch/43-residuum.tex				\
	chapters/040-analytisch/44-singulaer.tex			\
	chapters/040-analytisch/45-meromorph.tex			\
	chapters/040-analytisch/5-ganz.tex				\
	chapters/040-analytisch/51-definition.tex			\
	chapters/040-analytisch/52-cauchyliouville.tex			\
	chapters/040-analytisch/53-fundamentalsatz.tex			\
	chapters/040-analytisch/6-argument.tex				\
	chapters/040-analytisch/61-integral.tex				\
	chapters/040-analytisch/62-meromorph.tex			\
	chapters/040-analytisch/63-verallgemeinert.tex			\
	chapters/040-analytisch/chapter.tex

