#
# Makefile to create images
#
# (c) 2026 Prof Dr Andreas Müller
#
all:#
# Makefile to create images
#
# (c) 2026 Prof Dr Andreas Müller
#
all:	kontourintegral_fluegel.pdf

kontourintegral_fluegel.pdf: kontourintegral_fluegel.tex wing.tex
	pdflatex kontourintegral_fluegel.tex

fluegel_auftriebskraft.pdf: fluegel_auftriebskraft.tex wing.tex
	pdflatex fluegel_auftriebskraft.tex

