#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/050-differentialgleichungen/1-potenzreihen.tex		\
	chapters/050-differentialgleichungen/2-fuchs.tex		\
	chapters/050-differentialgleichungen/chapter.tex

