#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-elliptisch =						\
	papers/elliptisch/packages.tex					\
	papers/elliptisch/main.tex					\
	papers/elliptisch/references.bib				\
	papers/elliptisch/einleitung.tex				\
	papers/elliptisch/grenze.tex					\
	papers/elliptisch/funktionen.tex				\
	papers/elliptisch/anwendungen.tex

