#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-jordan =							\
	papers/jordan/packages.tex					\
	papers/jordan/main.tex						\
	papers/jordan/references.bib					\
	papers/jordan/01_satz.tex					\
	papers/jordan/02_konstruktion.tex				\
	papers/jordan/03_generalisierung.tex
