#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-jordan =							\
	papers/jordan/packages.tex					\
	papers/jordan/main.tex						\
	papers/jordan/references.bib					\
	papers/jordan/01_satz.tex					\
	papers/jordan/02_kreis.tex					\
	papers/jordan/03_konvexe_polygone.tex				\
	papers/jordan/04_einfache_polygone.tex				\
	papers/jordan/05_reell_analytische_kurven.tex			\
	papers/jordan/06_stueckweise_c1_kurven.tex			\
	papers/jordan/07_stetige_kurven.tex				\
	papers/jordan/08_verallgemeinerung.tex				\
	papers/jordan/09_schlusswort.tex
