#
# Makefile -- create images for chapter 4
#
# (c) 2026 Prof Dr Andreas Müller
#
all:	wege.pdf							\
	rechteck.pdf							\
	residuum.pdf							\
	argument.pdf							\
	lochgebiet.pdf							\
	homotopie.pdf							\
	dreiecke.pdf							\
	beliebig.pdf							\
	green.pdf							\
	deformation.pdf							\
	cauchyverteilung.pdf						\
	ecos.pdf

wege.pdf:	wege.tex
	pdflatex wege.tex

rechteck.pdf:	rechteck.tex
	pdflatex rechteck.tex

residuum.pdf:	residuum.tex
	pdflatex residuum.tex

argument.pdf:	argument.tex
	pdflatex argument.tex

lochgebiet.pdf:	lochgebiet.tex
	pdflatex lochgebiet.tex

homotopie.pdf:	homotopie.tex
	pdflatex homotopie.tex

dreiecke.pdf:	dreiecke.tex
	pdflatex dreiecke.tex

beliebig.pdf:	beliebig.tex
	pdflatex beliebig.tex

green.pdf:	green.tex
	pdflatex green.tex

deformation.pdf:	deformation.tex
	pdflatex deformation.tex

cauchyverteilung.pdf:	cauchyverteilung.tex
	pdflatex cauchyverteilung.tex

ecos.pdf:	ecos.tex
	pdflatex ecos.tex

