#
# Makefile
#
# (c) 2026 Prof Dr Andreas Müller
#
all:	rechtwinklig.pdf						\
	hoehe.pdf							\
	katheten.pdf

rechtwinklig.pdf:	rechtwinklig.tex
	pdflatex rechtwinklig.tex

hoehe.pdf:	hoehe.tex
	pdflatex hoehe.tex

katheten.pdf:	katheten.tex
	pdflatex katheten.tex


