#
# Makefile
#
# (c) 2026 Damien Flury, OST Ostschweizer Fachhochschule
#
all:	kehrwert.pdf kehrwert-symmetrisch.pdf ungerade.pdf

kehrwert.pdf:	kehrwert.tex
	pdflatex kehrwert.tex

kehrwert-symmetrisch.pdf:	kehrwert-symmetrisch.tex
	pdflatex kehrwert-symmetrisch.tex

ungerade.pdf:	ungerade.tex
	pdflatex ungerade.tex
