#
# Makefile
#
# (c) 2026 Prof Dr Andreas Müller
#
all:	invcis.pdf invtan.pdf lf0.pdf lfN.pdf lf.pdf

invcis.pdf:	invcis.tex
	pdflatex invcis.tex

invtan.pdf:	invtan.tex
	pdflatex invtan.tex

lf0.pdf:	lf0.tex
	pdflatex lf0.tex

lfN.pdf:	lfN.tex
	pdflatex lfN.tex

lf.pdf:	lf.tex
	pdflatex lf.tex
