#
# Makefile
#
# (c) 2026 Prof Dr Andreas Müller
#
all:	jordan_kurve.pdf	\
	beweis_kreis.pdf		\
	polygon_halbebene.pdf   \
	triangulierung.pdf      \
	strahlenparitaet.pdf    \
	tubulare_umgebung.pdf   \
	tangentenwindungszahl.pdf \
	umlaufzahl.pdf          \
	spitzen_ecken.pdf       \
	koch_schneeflocke.pdf   \
	polygonale_approximation.pdf \
	alexander_dualitaet.pdf \
	jordan_brouwer.pdf

jordan_kurve.pdf:	jordan_kurve.tex
	pdflatex jordan_kurve.tex

beweis_kreis.pdf:	beweis_kreis.tex
	pdflatex beweis_kreis.tex

polygon_halbebene.pdf:	polygon_halbebene.tex
	pdflatex polygon_halbebene.tex

triangulierung.pdf:	triangulierung.tex
	pdflatex triangulierung.tex

strahlenparitaet.pdf:	strahlenparitaet.tex
	pdflatex strahlenparitaet.tex

tubulare_umgebung.pdf:	tubulare_umgebung.tex
	pdflatex tubulare_umgebung.tex

tangentenwindungszahl.pdf:	tangentenwindungszahl.tex
	pdflatex tangentenwindungszahl.tex

umlaufzahl.pdf:	umlaufzahl.tex
	pdflatex umlaufzahl.tex

spitzen_ecken.pdf:	spitzen_ecken.tex
	pdflatex spitzen_ecken.tex

koch_schneeflocke.pdf:	koch_schneeflocke.tex
	pdflatex koch_schneeflocke.tex	

polygonale_approximation.pdf:	polygonale_approximation.tex
	pdflatex polygonale_approximation.tex

alexander_dualitaet.pdf:	alexander_dualitaet.tex
	pdflatex alexander_dualitaet.tex

jordan_brouwer.pdf:	jordan_brouwer.tex
	pdflatex jordan_brouwer.tex