#
# Makefile -- make file for the paper aircraft
# (c) 2020 Prof Dr Andreas Mueller
#
all:	eigenwerte.pdf komplexe-ebene.pdf dutchroll.pdf dutchroll-transparent.pdf flugzeugachsen.pdf

eigenwerte.pdf:	eigenwerte.tex
	pdflatex eigenwerte.tex

komplexe-ebene.pdf:	komplexe-ebene.tex
	pdflatex komplexe-ebene.tex

dutchroll.pdf: dutchroll.tex
	pdflatex dutchroll.tex

dutchroll-transparent.pdf: dutchroll-transparent.tex
	pdflatex dutchroll-transparent.tex

flugzeugachsen.pdf: flugzeugachsen.tex
	pdflatex flugzeugachsen.tex