#
# Makefile.inc -- Makefile dependencies for chapter 7
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/070-intalg/1-elementar.tex				\
	chapters/070-intalg/2-liouville.tex				\
	chapters/070-intalg/3-risch.tex					\
	chapters/070-intalg/chapter.tex

