#
# Makefile.inc -- Makefile dependencies for chapter 7
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/070-integration/1-elementar.tex			\
	chapters/070-integration/2-liouville.tex			\
	chapters/070-integration/3-risch.tex				\
	chapters/070-integration/chapter.tex

