#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/010-komplex/1-zahlen.tex				\
	chapters/010-komplex/2-funktionen.tex				\
	chapters/010-komplex/3-moebius.tex				\
	chapters/010-komplex/4-fundamental.tex				\
	chapters/010-komplex/fig/table-gold.tex				\
	chapters/010-komplex/chapter.tex

