#
# Makefile
#
# (c) 2026 Prof Dr Andreas Müller
#
all:	gausszahlen.pdf gaussebene.pdf

gausszahlen.pdf:	gausszahlen.tex
	pdflatex gausszahlen.tex

gaussebene.pdf:	gaussebene.tex
	pdflatex gaussebene.tex

