#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-hauptwert =						\
	papers/hauptwert/packages.tex					\
	papers/hauptwert/main.tex					\
	papers/hauptwert/references.bib				\
	papers/hauptwert/motivation-definition.tex			\
	papers/hauptwert/reelle-beispiele.tex				\
	papers/hauptwert/hauptwerte-residuen.tex			\
	papers/hauptwert/teil3.tex					\
	papers/hauptwert/fig/kehrwert.tex				\
	papers/hauptwert/fig/kehrwert-symmetrisch.tex			\
	papers/hauptwert/fig/nichtungerade.tex				\
	papers/hauptwert/fig/pol-innen.tex				\
	papers/hauptwert/images/kehrwert.pdf				\
	papers/hauptwert/images/kehrwert-symmetrisch.pdf		\
	papers/hauptwert/images/nichtungerade.pdf			\
	papers/hauptwert/images/pol-innen.pdf

