#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/030-integration/1-wegintegral.tex			\
	chapters/030-integration/2-cauchy.tex				\
	chapters/030-integration/3-residuen.tex				\
	chapters/030-integration/chapter.tex

